change wording

diff --git a/espresso/.githooks/pre-commit b/espresso/.githooks/pre-commit
--- a/espresso/.githooks/pre-commit
+++ b/espresso/.githooks/pre-commit
@@ -4,4 +4,6 @@ if git diff --cached --name-only | grep -q "^espresso/.env$"; then
   echo "You MUST also update image versions in tee-op-deploy, or create a ticket there."
   echo "See .env header for details."
   echo "After either updating tee-op-deploy or create a ticket, commit with: git commit --no-verify"
+  echo "Commit aborted."
+  exit 1
 fi
